### ISSUE TITLE
Feature: Highlight the current day and time

### ISSUE THREAD

**Issue by jstsddg** [patrickstecker/Vorlesungsplan#19]
Highlight the current day in a different color and also the current time, for example:
- when there currently is a course: highlight the course in a different color
- when there is currently no course: put a colored line above the next course or below the lat course

Feedback for different highlighting is appreciated.

**Comment by patrickstecker** [comment]
What about marking the current course in a green color? Need to find a eye-friendly one

**Comment by jstsddg** [comment]
I think we should stick to red, as this is the main design color.
Furthermore I think red and green do not go together really nicely.

**Comment by patrickstecker** [comment]
Sounds good, we currently have a branch called feature/time-estimation. In this branch I implemented that a VorlesungsplanItem holds a value about its progress from 0 to 100. Maybe you can use this when it is on master

Edit: This feature is now on Master and ready to use

**Comment by felixwortmann** [comment]
Is this finished @MrKraboom ?

**Comment by jstsddg** [comment]
@felixwortmann 
@patrickstecker implemented a progressbar in #20 , but I think we are still missing something to indicate the current day.

**Comment by patrickstecker** [comment]
created branch feature/mark-current-day for this issue, any suggestions how to mark it?

**Comment by jstsddg** [comment]
@patrickstecker 
Maybe the background color of the day / course can be changed to a light version of the `@color/date_title_color` color?

**Comment by patrickstecker** [comment]
I'll try that:D

**Comment by patrickstecker** [comment]
@MrKraboom didnt get how i change the full background, wanna try?

**Comment by jstsddg** [comment]
@patrickstecker 
I will have a look. :)

**Comment by jstsddg** [comment]
@patrickstecker 
I added a commit to #41 
Maybe you can work with that
